export const FETCH_DRINKS_START = "FETCH_DRINKS_START";
export const FETCH_DRINKS_SUCCESS = "FETCH_DRINKS_SUCCESS";
export const FETCH_DRINKS_FAIL = "FETCH_DRINKS_FAIL";

export const FETCH_FOOD_START = "FETCH_FOOD_START";
export const FETCH_FOOD_SUCCESS = "FETCH_FOOD_SUCCESS";
export const FETCH_FOOD_FAIL = "FETCH_FOOD_FAIL";

export const ADD_ORDER_DRINK = "ADD_ORDER_DRINK"; 
export const REMOVE_ORDER_DRINK = "REMOVE_ORDER_DRINK";

export const ADD_ORDER_FOOD = "ADD_ORDER_FOOD"; 
export const REMOVE_ORDER_FOOD = "REMOVE_ORDER_FOOD";

export const SELECTED_TABLE = "SELECTED_TABLE";
export const UNSELECTED_TABLE = "UNSELECTED_TABLE";

export const ADD_TABLE = "ADD_TABLE"; 
export const REMOVE_TABLE = "REMOVE_TABLE";